version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: bpkh
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge